import './globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import Providers from '@/components/Providers';
import { Container, Navigation, Footer } from '@layout';

export const metadata: Metadata = {
  title: 'Bruno Erceg - React Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@300..800&family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-background relative flex min-h-screen dark:bg-slate-900">
        <Providers>
          <Toaster position="top-center" richColors />
          <Container className="flex flex-col justify-between lg:w-[1300px]">
            <Navigation className="mt-4 mb-15 md:mb-30" />
            <main className="grow">{children}</main>
            <Footer />
            <div className="fixed bottom-0 left-0 z-50 h-7 w-full to-transparent mask-[linear-gradient(to_top,black_0%,transparent_100%)] backdrop-blur-sm" />
          </Container>
        </Providers>
      </body>
    </html>
  );
}
