import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Bruno Erceg - React Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@300..800&family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        />{' '}
      </head>
      <body className="relative">
        <div className="fixed bottom-0 left-0 z-50 h-7 w-full to-transparent mask-[linear-gradient(to_top,black_0%,transparent_100%)] backdrop-blur-sm" />
        {children}
      </body>
    </html>
  );
}
